from enum import Enum

CODE_ANSWER = 0x80

class ProtocolCode(Enum):
    PROTOCOL_TEST_REQ = 0x01
    PROTOCOL_FILE_REQ = 0x02

    PROTOCOL_TEST_ASW = PROTOCOL_TEST_REQ + CODE_ANSWER
    PROTOCOL_FILE_ASW = PROTOCOL_FILE_REQ + CODE_ANSWER